# Generated by Django 5.2.14 on 2026-09-03 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=16)),
                ('action', models.CharField(db_index=True, max_length=48)),
                ('target_kind', models.CharField(blank=True, choices=[('finding', 'Finding'), ('receipt', 'Receipt'), ('comment', 'Comment'), ('attachment', 'Attachment'), ('link', 'Link')], default='', max_length=16)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('target_ref', models.CharField(blank=True, default='', max_length=300)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('console', 'Console'), ('mcp', 'MCP / service token'), ('bulk', 'Bulk action'), ('system', 'System')], default='console', max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity event',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['target_kind', 'target_id', '-occurred_at'], name='activity_ac_target__853746_idx'), models.Index(fields=['actor', '-occurred_at'], name='activity_ac_actor_db0329_idx')],
            },
        ),
    ]
