# Generated by Django 5.2.14 on 2026-09-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='target_kind',
            field=models.CharField(blank=True, choices=[('finding', 'Finding'), ('receipt', 'Receipt'), ('comment', 'Comment'), ('cube_comment', 'Cube comment'), ('attachment', 'Attachment'), ('link', 'Link')], default='', max_length=16),
        ),
    ]
