# Generated by Django 5.2.8 on 2026-02-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_data', '0003_add_journal_type_to_journals'),
        ('xero_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerojournals',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact/customer (set for manual journals from API; transaction lines get it via transaction_source)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journals', to='xero_metadata.xerocontacts'),
        ),
    ]
