# Generated by Django 5.2.8 on 2026-02-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_data', '0004_add_contact_to_xero_journals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerojournals',
            name='journal_id',
            field=models.CharField(max_length=200),
        ),
    ]
