# Generated by Django 5.2.8 on 2026-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_data', '0007_add_fin_year_fin_period_to_journal_drill_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerojournals',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Negative portion of amount (credit <= 0). debit + credit = amount.', max_digits=30),
        ),
        migrations.AddField(
            model_name='xerojournals',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive portion of amount (debit >= 0). debit + credit = amount.', max_digits=30),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE xero_data_xerojournals
                SET debit  = GREATEST(amount, 0),
                    credit = LEAST(amount, 0)
                WHERE debit = 0 AND credit = 0 AND amount != 0;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
