# Generated by Django 5.2.8 on 2026-03-12 19:05

import apps.xero.xero_data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0003_add_fiscal_year_start_month'),
        ('xero_data', '0009_add_debit_credit_to_journal_drill_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, max_length=500, upload_to=apps.xero.xero_data.models.xero_document_upload_to)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('xero_attachment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xero_documents', to='xero_core.xerotenant')),
                ('transaction_source', models.ForeignKey(help_text='The Xero transaction (invoice, credit note, bank transaction, etc.) this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='xero_data.xerotransactionsource')),
            ],
            options={
                'verbose_name': 'Xero Document',
                'verbose_name_plural': 'Xero Documents',
                'ordering': ['transaction_source', 'file_name'],
                'unique_together': {('transaction_source', 'file_name')},
            },
        ),
    ]
