# Generated by Codex on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0003_add_fiscal_year_start_month'),
        ('xero_data', '0010_add_xero_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroJournalExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type', models.CharField(blank=True, default='', max_length=20)),
                ('journal_number', models.IntegerField(blank=True, null=True)),
                ('journal_id', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('reference', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_exclusions', to='xero_core.xerotenant')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['organisation', 'active'], name='jrnl_excl_org_active_idx'),
                    models.Index(fields=['organisation', 'date', 'journal_number'], name='jrnl_excl_org_dt_num_idx'),
                ],
            },
        ),
    ]
