# Generated by Django 5.2.14 on 2026-06-03 08:51

import apps.xero.xero_data.models
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0003_add_fiscal_year_start_month'),
        ('xero_data', '0012_add_aged_reports'),
        ('xero_metadata', '0003_use_tracking_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerodocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/app/media/xero_documents'), upload_to=apps.xero.xero_data.models.xero_document_upload_to),
        ),
        migrations.CreateModel(
            name='XeroQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(help_text='Xero QuoteID (UUID)', max_length=64)),
                ('quote_number', models.CharField(blank=True, default='', max_length=100)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('xero_contact_id', models.CharField(blank=True, default='', help_text='Denormalised contact UUID for fast lookup even if XeroContacts row is missing', max_length=64)),
                ('contact_name', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('DECLINED', 'Declined'), ('ACCEPTED', 'Accepted'), ('INVOICED', 'Invoiced'), ('DELETED', 'Deleted')], db_index=True, default='DRAFT', max_length=20)),
                ('date', models.DateField(blank=True, db_index=True, help_text='Quote date', null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, default='', max_length=3)),
                ('currency_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('sub_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('terms', models.TextField(blank=True, default='')),
                ('line_amount_types', models.CharField(blank=True, default='', help_text='Exclusive | Inclusive | NoTax', max_length=20)),
                ('branding_theme_id', models.CharField(blank=True, default='', max_length=64)),
                ('updated_date_utc', models.DateTimeField(blank=True, db_index=True, help_text='Xero UpdatedDateUTC — drives incremental sync', null=True)),
                ('collection', models.JSONField(blank=True, help_text='Raw Xero response — forward-compat for fields we did not denormalise', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_quotes', to='xero_metadata.xerocontacts')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xero_quotes', to='xero_core.xerotenant')),
            ],
            options={
                'verbose_name': 'Xero Quote',
                'verbose_name_plural': 'Xero Quotes',
                'ordering': ['-date', '-updated_date_utc'],
            },
        ),
        migrations.CreateModel(
            name='XeroQuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_id', models.CharField(blank=True, default='', help_text='Xero LineItemID — optional', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unit_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('item_code', models.CharField(blank=True, default='', help_text='Links to future XeroItem table when imported', max_length=100)),
                ('account_code', models.CharField(blank=True, default='', help_text='Denormalised Xero account code', max_length=20)),
                ('tax_type', models.CharField(blank=True, default='', max_length=50)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('line_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Preserve Xero line order')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='xero_metadata.xeroaccount')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='xero_data.xeroquote')),
                ('tracking1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='xero_metadata.xerotracking')),
                ('tracking2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='xero_metadata.xerotracking')),
            ],
            options={
                'verbose_name': 'Xero Quote Line Item',
                'verbose_name_plural': 'Xero Quote Line Items',
                'ordering': ['quote', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='xeroquote',
            index=models.Index(fields=['organisation', 'status', 'date'], name='xd_quote_org_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroquote',
            index=models.Index(fields=['organisation', 'updated_date_utc'], name='xd_quote_org_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroquote',
            index=models.Index(fields=['organisation', 'xero_contact_id'], name='xd_quote_org_xcontact_idx'),
        ),
        migrations.AddConstraint(
            model_name='xeroquote',
            constraint=models.UniqueConstraint(fields=('organisation', 'quote_id'), name='xero_data_quote_org_quoteid_uniq'),
        ),
        migrations.AddIndex(
            model_name='xeroquotelineitem',
            index=models.Index(fields=['quote', 'position'], name='xd_quote_li_qpos_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroquotelineitem',
            index=models.Index(fields=['account_code'], name='xd_quote_li_acctcode_idx'),
        ),
    ]
