# Generated by Django 5.2.14 on 2026-06-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0003_add_fiscal_year_start_month'),
        ('xero_data', '0013_xero_quotes'),
        ('xero_metadata', '0003_use_tracking_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(help_text='Xero InvoiceID (UUID)', max_length=64)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('ACCREC', 'Accounts Receivable (Sales Invoice)'), ('ACCPAY', 'Accounts Payable (Bill)')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AUTHORISED', 'Authorised'), ('PAID', 'Paid'), ('VOIDED', 'Voided'), ('DELETED', 'Deleted')], db_index=True, default='DRAFT', max_length=20)),
                ('xero_contact_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('contact_name', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('fully_paid_on_date', models.DateField(blank=True, null=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('planned_payment_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, default='', max_length=3)),
                ('currency_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('sub_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('amount_due', models.DecimalField(db_index=True, decimal_places=4, default=0, help_text='Outstanding balance — drives aged-AR/AP queries', max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('amount_credited', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('line_amount_types', models.CharField(blank=True, default='', help_text='Exclusive | Inclusive | NoTax', max_length=20)),
                ('branding_theme_id', models.CharField(blank=True, default='', max_length=64)),
                ('url', models.TextField(blank=True, default='', help_text='Xero deep-link URL')),
                ('sent_to_contact', models.BooleanField(default=False)),
                ('is_discounted', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
                ('updated_date_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('collection', models.JSONField(blank=True, help_text='Raw Xero response — includes Payments[], CreditNotes[], Prepayments[], Overpayments[] arrays not yet denormalised.', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_invoices', to='xero_metadata.xerocontacts')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xero_invoices', to='xero_core.xerotenant')),
            ],
            options={
                'verbose_name': 'Xero Invoice',
                'verbose_name_plural': 'Xero Invoices',
                'ordering': ['-date', '-updated_date_utc'],
            },
        ),
        migrations.CreateModel(
            name='XeroInvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_id', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unit_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('account_code', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('tax_type', models.CharField(blank=True, default='', max_length=50)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('line_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='xero_metadata.xeroaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='xero_data.xeroinvoice')),
                ('tracking1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='xero_metadata.xerotracking')),
                ('tracking2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='xero_metadata.xerotracking')),
            ],
            options={
                'verbose_name': 'Xero Invoice Line Item',
                'verbose_name_plural': 'Xero Invoice Line Items',
                'ordering': ['invoice', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='xeroinvoice',
            index=models.Index(fields=['organisation', 'type', 'status', 'date'], name='xd_inv_org_type_stat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroinvoice',
            index=models.Index(fields=['organisation', 'type', 'status', 'amount_due'], name='xd_inv_org_type_stat_due_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroinvoice',
            index=models.Index(fields=['organisation', 'xero_contact_id'], name='xd_inv_org_xcontact_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroinvoice',
            index=models.Index(fields=['organisation', 'updated_date_utc'], name='xd_inv_org_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroinvoice',
            index=models.Index(fields=['organisation', 'due_date'], name='xd_inv_org_duedate_idx'),
        ),
        migrations.AddConstraint(
            model_name='xeroinvoice',
            constraint=models.UniqueConstraint(fields=('organisation', 'invoice_id'), name='xero_data_invoice_org_invoiceid_uniq'),
        ),
        migrations.AddIndex(
            model_name='xeroinvoicelineitem',
            index=models.Index(fields=['invoice', 'position'], name='xd_inv_li_ipos_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroinvoicelineitem',
            index=models.Index(fields=['account_code'], name='xd_inv_li_acctcode_idx'),
        ),
    ]
