# Generated by Django 5.2.17 on 2026-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0004_add_tenant_reauth_flags'),
        ('xero_data', '0014_xero_invoices'),
        ('xero_metadata', '0003_use_tracking_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerotransactionsource',
            name='attachments_checked_at',
            field=models.DateTimeField(blank=True, help_text='When HasAttachments was last read from a Xero list response (or the Attachments list).', null=True),
        ),
        migrations.AddField(
            model_name='xerotransactionsource',
            name='has_attachments',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='xerotransactionsource',
            index=models.Index(fields=['organisation', 'has_attachments'], name='xero_txsrc_org_hasatt_idx'),
        ),
    ]
