# Generated by Django 5.2.14 on 2026-08-22 00:35

import apps.xero.xero_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_data', '0016_drill_view_exclude_legacy_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerodocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, storage=apps.xero.xero_data.models._xero_documents_storage, upload_to=apps.xero.xero_data.models.xero_document_upload_to),
        ),
    ]
