# Generated by Django 5.2.14 on 2026-09-03 11:50

from django.db import migrations, models


def backfill_synced_at(apps, schema_editor):
    """Stamp every existing transaction source as "just synced".

    The trail balance build treats rows with synced_at after its last-run
    stamp as touched. With all rows stamped now, the first build after this
    deploys sees everything touched and does one full reprocess + full
    rebuild (exactly what every build did before), which also establishes a
    clean baseline; from the second build on it is incremental. Leaving the
    column NULL would instead make that first build skip rows synced between
    the previous build and the deploy.
    """
    XeroTransactionSource = apps.get_model('xero_data', 'XeroTransactionSource')
    from django.utils import timezone
    XeroTransactionSource.objects.filter(synced_at__isnull=True).update(synced_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0005_xeroapiquota'),
        ('xero_data', '0017_alter_xerodocument_file'),
        ('xero_metadata', '0003_use_tracking_category_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='xerojournals',
            name='journals_org_dt_acc_idx',
        ),
        migrations.AddField(
            model_name='xerotransactionsource',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='When this row was last written from a Xero list response. The trail balance build compares it with its own last-run stamp to reprocess only the transactions that changed since, instead of all of them.', null=True),
        ),
        migrations.AddIndex(
            model_name='xerotransactionsource',
            index=models.Index(fields=['organisation', 'synced_at'], name='xero_txsrc_org_synced_idx'),
        ),
        migrations.RunPython(backfill_synced_at, migrations.RunPython.noop),
    ]
