-- =============================================================================
-- RAG pgvector store: documents table @ bge-m3 (1024-dim)
-- =============================================================================
-- Target DB:   the Django default database (klikk_financials_v4) — the rag/
--              pipeline resolves pg_bi_* == default DB and rag_schema == 'public'
--              (see apps/ai_agent/agent/config.py).
-- Owned by:    the rag/ pipeline (embedder.py / indexer.py / retriever.py).
--              This table is NOT a Django model and is intentionally unmanaged
--              by Django migrations — it is provisioned out-of-band via this
--              script, consistent with how the rag/ pipeline is operated.
--
-- Why this script exists:
--   The embedder was upgraded all-MiniLM-L6-v2 (384-dim) -> BAAI/bge-m3 (1024-dim).
--   pgvector columns are fixed-dimension, so a dim change cannot be done with a
--   plain ALTER; the embedding column (and its ANN index) must be (re)created at
--   the new dimension. Any pre-existing 384-dim vectors are discarded — they are
--   regenerated from source by a full reindex (rag_reindex --full).
--
-- Idempotency:
--   Safe to run repeatedly. On an existing 384-dim table this DROPs and recreates
--   the embedding column + index at 1024-dim (destroying old vectors by design).
--   On a fresh DB it creates the whole table. After running, ALWAYS reindex.
--
-- DISTANCE METRIC: cosine. bge-m3 outputs L2-normalised vectors and the retriever
--   queries with `<=>` (cosine distance), so the HNSW index uses vector_cosine_ops.
-- =============================================================================

BEGIN;

-- pgvector extension (no-op if already present; 0.8.x is installed on staging).
CREATE EXTENSION IF NOT EXISTS vector;

-- 1) Create the table if it does not exist (fresh DB / staging where the rag/
--    pgvector store was never provisioned). embedding is vector(1024).
CREATE TABLE IF NOT EXISTS public.documents (
    doc_id      text PRIMARY KEY,
    source_path text,
    doc_type    text,
    title       text,
    content     text,
    embedding   vector(1024),
    metadata    jsonb DEFAULT '{}'::jsonb,
    indexed_at  timestamptz NOT NULL DEFAULT now()
);

-- 2) If the table already existed with a different-dimension embedding column
--    (e.g. vector(384) from the MiniLM era), recreate the column at 1024-dim.
--    We DROP rather than ALTER because pgvector cannot change a column's
--    dimension in place. Existing vectors are discarded (regenerated by reindex).
DO $$
DECLARE
    current_dim integer;
BEGIN
    SELECT a.atttypmod
      INTO current_dim
      FROM pg_attribute a
      JOIN pg_class c     ON c.oid = a.attrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public'
       AND c.relname = 'documents'
       AND a.attname = 'embedding'
       AND NOT a.attisdropped;

    -- For pgvector, atttypmod holds the declared dimension directly.
    IF current_dim IS NOT NULL AND current_dim <> 1024 THEN
        RAISE NOTICE 'documents.embedding is dim=% — recreating at 1024-dim (old vectors discarded).', current_dim;
        DROP INDEX IF EXISTS public.documents_embedding_hnsw_idx;
        ALTER TABLE public.documents DROP COLUMN embedding;
        ALTER TABLE public.documents ADD COLUMN embedding vector(1024);
    END IF;
END $$;

-- 3) ANN index for cosine similarity search (matches retriever's `<=>`).
--    HNSW: good recall/latency for the small/medium doc counts this store holds.
--    Created AFTER the column is guaranteed to be 1024-dim.
CREATE INDEX IF NOT EXISTS documents_embedding_hnsw_idx
    ON public.documents
    USING hnsw (embedding vector_cosine_ops);

-- 4) Helper index on doc_type for the retriever's optional filtering / debugging.
CREATE INDEX IF NOT EXISTS documents_doc_type_idx
    ON public.documents (doc_type);

COMMIT;

-- =============================================================================
-- POST-MIGRATION (run separately, NOT inside this transaction):
--   python manage.py rag_reindex --full --pg-host <host>
-- to repopulate public.documents with bge-m3 (1024-dim) vectors.
-- =============================================================================
