"""
Create ``pricelist_pricelistitem`` and ``pricelist_pricelistprice``.

Produced by ``makemigrations`` and then edited to prepend ``BtreeGistExtension``.
It is generated rather than hand-written on purpose: the exclusion constraint
below deconstructs to an exact Q-argument order that is easy to get wrong by
hand, and a mismatch makes ``makemigrations --check pricelist`` dirty forever.

* ``BtreeGistExtension`` must run FIRST. ``pricelist_no_overlapping_list_price``
  mixes a range operator (``&&`` on a daterange) with an equality operator
  (``=`` on the ``item_id`` bigint) in ONE GiST index; Postgres cannot put ``=``
  on a scalar into a GiST index without the ``btree_gist`` extension.
* ``pricelist_price_valid_range`` — ``valid_to`` is NULL (open) or >= ``valid_from``.
* ``pricelist_no_overlapping_list_price`` — for the general LIST lane
  (``price_type='LIST' AND customer_id IS NULL``) no two rows for the same item
  may have overlapping ``daterange(valid_from, valid_to, '[]')``. A NULL
  ``valid_to`` is unbounded above, so the open row collides with any later-dated
  row until ``services.add_price`` closes it. TRADE / SPECIAL and
  customer-specific lanes are deliberately NOT covered — they are overrides and
  ``services.get_price`` picks the newest.

Reverse drops both tables; the extension is left in place.
"""
# Generated by Django 5.2.17 on 2026-08-19 17:01

import django.contrib.postgres.constraints
import django.contrib.postgres.operations
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xero_data', '0015_transactionsource_has_attachments'),
        ('xero_metadata', '0003_use_tracking_category_id'),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Short slug, e.g. DB-V10P. Upper-cased on save.', max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PA', 'PA tops / subs'), ('AMP', 'Amplifiers'), ('DJ', 'DJ gear'), ('PROJECTOR', 'Projectors'), ('LENS', 'Projector lenses'), ('LIGHTING', 'Lighting'), ('STAGING', 'Staging'), ('RIGGING', 'Rigging'), ('CABLING', 'Cabling & consumables'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=16)),
                ('unit', models.CharField(choices=[('DAY', 'Per day'), ('EVENT', 'Per event'), ('WEEK', 'Per week'), ('SEASON', 'Per season')], default='DAY', max_length=16)),
                ('qty_owned', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('xero_account_code', models.CharField(blank=True, default='', help_text='Xero account the asset was capitalised to, e.g. EE-SE01 Event Equipment @ Cost.', max_length=20)),
                ('xero_tracking_option_id', models.CharField(blank=True, default='', help_text='xero_metadata_xerotracking.option_id of the Profit Center this asset earns under.', max_length=64)),
                ('xero_fixed_asset_id', models.UUIDField(blank=True, help_text="Xero Fixed Assets register AssetId. TODO: not populated — the Xero app has no 'assets.read' scope and there is no local fixed-asset mirror table. See docs/pricelist.md.", null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xero_purchase_line', models.ForeignKey(blank=True, help_text='The supplier-bill line the asset was bought on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricelist_items', to='xero_data.xeroinvoicelineitem')),
            ],
            options={
                'verbose_name': 'Price list item',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PriceListPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ex VAT, ZAR.', max_digits=12)),
                ('valid_from', models.DateField(db_index=True)),
                ('valid_to', models.DateField(blank=True, help_text='Inclusive last day; NULL = still current.', null=True)),
                ('price_type', models.CharField(choices=[('LIST', 'List'), ('TRADE', 'Trade'), ('SPECIAL', 'Special')], db_index=True, default='LIST', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('set_by', models.CharField(blank=True, default='', help_text="'mc' / 'claude-mcp' / username", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, help_text='NULL = applies to everyone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricelist_prices', to='xero_metadata.xerocontacts')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricelist.pricelistitem')),
            ],
            options={
                'verbose_name': 'Price list price',
                'ordering': ['item', '-valid_from', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='pricelist_price_valid_range'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('customer__isnull', True), ('price_type', 'LIST')), expressions=[(models.Func(models.F('valid_from'), models.F('valid_to'), models.Value('[]'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&'), ('item', '=')], name='pricelist_no_overlapping_list_price')],
            },
        ),
    ]
