# Generated by Django 5.2.14 on 2026-06-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investec', '0025_investecbankaccount_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('income', 'Income'), ('transfer', 'Transfer'), ('review', 'Review')], db_index=True, default='personal', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('type', 'name'), name='pe_category_type_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, help_text='Stored UPPERCASE; substring-matched against the description.', max_length=120)),
                ('transaction_type', models.CharField(blank=True, db_index=True, help_text='Investec transaction_type to gate on (CardPurchases, OnlineBankingPayments, ...). Blank = any.', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=0, help_text='Tie-breaker when two tags are the same length; higher wins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='personal_expenses.category')),
            ],
            options={
                'verbose_name': 'Classification Rule',
                'verbose_name_plural': 'Classification Rules',
                'ordering': ['-priority', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='TransactionClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('matched_tag', models.CharField(blank=True, help_text='The rule tag that matched (provenance / debugging).', max_length=120)),
                ('classified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classifications', to='personal_expenses.category')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='personal_expenses.classificationrule')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='investec.investecbanktransaction')),
            ],
            options={
                'verbose_name': 'Transaction Classification',
                'verbose_name_plural': 'Transaction Classifications',
            },
        ),
        migrations.AddConstraint(
            model_name='classificationrule',
            constraint=models.UniqueConstraint(fields=('tag', 'transaction_type'), name='pe_rule_tag_tt_unique'),
        ),
        migrations.AddIndex(
            model_name='transactionclassification',
            index=models.Index(fields=['category', 'is_manual'], name='personal_ex_categor_4d6c3d_idx'),
        ),
    ]
