# Generated by Cursor on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='memory',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

