# Generated by Cursor on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0004_agentproject_and_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdocument',
            name='pin_to_context',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemdocument',
            name='context_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='systemdocument',
            index=models.Index(fields=['project', 'pin_to_context', 'context_order'], name='ai_agent_sy_project_6c9d91_idx'),
        ),
    ]

