# Generated by Cursor on 2026-02-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0005_systemdocument_pin_to_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_knowledge_corpora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgecorpus',
            index=models.Index(fields=['slug'], name='ai_agent_kn_slug_7d6d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecorpus',
            index=models.Index(fields=['is_active'], name='ai_agent_kn_is_acti_9b747b_idx'),
        ),
        migrations.AddField(
            model_name='systemdocument',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_documents', to='ai_agent.knowledgecorpus'),
        ),
        migrations.AddIndex(
            model_name='systemdocument',
            index=models.Index(fields=['corpus', 'project'], name='ai_agent_sy_corpus__b5b0a1_idx'),
        ),
        migrations.AddField(
            model_name='agentproject',
            name='default_corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_projects', to='ai_agent.knowledgecorpus'),
        ),
        migrations.CreateModel(
            name='KnowledgeChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=120)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedded_at', models.DateTimeField(auto_now=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_agent.knowledgecorpus')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='ai_agent.agentproject')),
                ('system_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='ai_agent.systemdocument')),
            ],
            options={
                'ordering': ['system_document_id', 'chunk_index'],
                'unique_together': {('system_document', 'embedding_model', 'chunk_index')},
            },
        ),
        migrations.AddIndex(
            model_name='knowledgechunkembedding',
            index=models.Index(fields=['corpus', 'project', 'system_document'], name='ai_agent_kn_corpus__5d0e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunkembedding',
            index=models.Index(fields=['corpus', 'embedding_model'], name='ai_agent_kn_corpus__5b6f3a_idx'),
        ),
    ]

