# Generated by Django 5.2.8 on 2026-02-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0006_knowledge_corpus_and_embeddings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryRefreshRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('organisation_id', models.IntegerField(blank=True, help_text='XeroTenant id that changed; null = refresh for all orgs', null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='agentproject',
            new_name='ai_agent_ag_slug_9006ee_idx',
            old_name='ai_agent_ag_slug_f4ad1b_idx',
        ),
        migrations.RenameIndex(
            model_name='agentproject',
            new_name='ai_agent_ag_is_acti_f7fa4b_idx',
            old_name='ai_agent_ag_is_acti_9fe1d1_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgechunkembedding',
            new_name='ai_agent_kn_corpus__150175_idx',
            old_name='ai_agent_kn_corpus__5d0e5b_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgechunkembedding',
            new_name='ai_agent_kn_corpus__9572ea_idx',
            old_name='ai_agent_kn_corpus__5b6f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgecorpus',
            new_name='ai_agent_kn_slug_493d73_idx',
            old_name='ai_agent_kn_slug_7d6d8c_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgecorpus',
            new_name='ai_agent_kn_is_acti_f78cea_idx',
            old_name='ai_agent_kn_is_acti_9b747b_idx',
        ),
        migrations.RenameIndex(
            model_name='systemdocument',
            new_name='ai_agent_sy_slug_6e2bed_idx',
            old_name='ai_agent_sy_slug_ae50a8_idx',
        ),
        migrations.RenameIndex(
            model_name='systemdocument',
            new_name='ai_agent_sy_is_acti_782755_idx',
            old_name='ai_agent_sy_is_acti_04b268_idx',
        ),
        migrations.RenameIndex(
            model_name='systemdocument',
            new_name='ai_agent_sy_project_c2dd7d_idx',
            old_name='ai_agent_sy_project_6c9d91_idx',
        ),
        migrations.RenameIndex(
            model_name='systemdocument',
            new_name='ai_agent_sy_corpus__ebd73c_idx',
            old_name='ai_agent_sy_corpus__b5b0a1_idx',
        ),
    ]
