# Generated by Django 5.2.11 on 2026-03-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0007_add_glossary_refresh_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. "anthropic_api_key"', max_length=120, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('label', models.CharField(blank=True, default='', help_text='Human-readable label', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GlobalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Embedding vector as list of floats')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(help_text='e.g. "web_search"', max_length=120, unique=True)),
                ('import_path', models.CharField(help_text='e.g. "apps.ai_agent.skills.web_search"', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Routing keywords (list of strings)')),
                ('always_on', models.BooleanField(default=False, help_text='Always include in tool routing')),
                ('enabled', models.BooleanField(default=True, help_text='Load this skill at startup')),
                ('sort_order', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Registry Entry',
                'verbose_name_plural': 'Skill Registry',
                'ordering': ['sort_order', 'module_name'],
            },
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_external_id', models.CharField(blank=True, default='', help_text='Session ID from external source (e.g. FastAPI chat)', max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_contexts', to='ai_agent.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentViewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_name', models.CharField(max_length=255)),
                ('server_name', models.CharField(blank=True, default='', max_length=255)),
                ('query_state', models.TextField(blank=True, default='', help_text='JSON-encoded PAW query state')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_states', to='ai_agent.agentsession')),
            ],
            options={
                'unique_together': {('session', 'cube_name', 'server_name')},
            },
        ),
    ]
