# Generated by Django 5.2.14 on 2026-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0008_credential_globalcontext_skillregistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryrefreshrequest',
            name='tenant_id',
            field=models.CharField(blank=True, help_text='XeroTenant.tenant_id that changed; null = refresh for all orgs', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='glossaryrefreshrequest',
            name='organisation_id',
            field=models.IntegerField(blank=True, help_text='DEPRECATED — wrong type for a Xero tenant id. Use tenant_id.', null=True),
        ),
    ]
