# Generated by Django 5.2.14 on 2026-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard'), ('auditor', 'Auditor')], default='standard', max_length=16),
        ),
    ]
