# Generated by Django 5.2.17 on 2026-08-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlipComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slip comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlipReview',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('to_process', models.BooleanField(default=False)),
                ('decision', models.CharField(blank=True, choices=[('', 'Undecided'), ('CAPTURE', 'Capture in Xero'), ('MEAL_SKIP', 'Meal — skip'), ('PERSONAL', 'Personal'), ('DUPLICATE', 'Duplicate'), ('ALREADY_IN_XERO', 'Already in Xero')], default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slip review',
            },
        ),
    ]
