# Generated by Django 5.2.14 on 2026-09-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_slipreview_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='receipts.slipcomment'),
        ),
    ]
