# Generated by Django 5.2.14 on 2026-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_slipcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slipcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
