# Generated by Django 5.2.8 on 2026-02-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0002_use_tracking_category_id'),
        ('xero_sync', '0010_simplify_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerolastupdate',
            name='end_point',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('contacts', 'Contacts'), ('tracking_categories', 'Tracking Categories'), ('journals', 'Journals'), ('manual_journals', 'Manual Journals'), ('profit_loss', 'Profit & Loss'), ('bank_transactions', 'Bank Transactions'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('credit_notes', 'Credit Notes'), ('prepayments', 'Prepayments'), ('overpayments', 'Overpayments')], max_length=100),
        ),
        migrations.CreateModel(
            name='XeroApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('metadata', 'Update Metadata'), ('data', 'Sync Transactions & Journals'), ('journals', 'Process Journals'), ('trail-balance', 'Build Trail Balance'), ('pnl-by-tracking', 'Import P&L by Tracking'), ('reconcile', 'Reconcile Reports')], max_length=50)),
                ('api_calls', models.IntegerField(default=0, help_text='Number of Xero API calls made in this run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_call_logs', to='xero_core.xerotenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['process', 'created_at'], name='api_call_process_date_idx'), models.Index(fields=['tenant', 'created_at'], name='api_call_tenant_date_idx')],
            },
        ),
    ]
