# Generated by Django 5.2.17 on 2026-08-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_sync', '0011_add_xero_api_call_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeroapicalllog',
            name='process',
            field=models.CharField(choices=[('metadata', 'Update Metadata'), ('data', 'Sync Transactions & Journals'), ('journals', 'Process Journals'), ('trail-balance', 'Build Trail Balance'), ('pnl-by-tracking', 'Import P&L by Tracking'), ('reconcile', 'Reconcile Reports'), ('invoices', 'Sync Invoices'), ('quotes', 'Sync Quotes'), ('documents', 'Document Sync')], max_length=50),
        ),
        migrations.AlterField(
            model_name='xerolastupdate',
            name='end_point',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('contacts', 'Contacts'), ('tracking_categories', 'Tracking Categories'), ('journals', 'Journals'), ('manual_journals', 'Manual Journals'), ('profit_loss', 'Profit & Loss'), ('bank_transactions', 'Bank Transactions'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('credit_notes', 'Credit Notes'), ('prepayments', 'Prepayments'), ('overpayments', 'Overpayments'), ('invoice_store', 'Invoice Store Sync'), ('process_journals', 'Process Journals')], max_length=100),
        ),
    ]
