# Generated by Django 5.2.17 on 2026-08-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_sync', '0012_alter_xeroapicalllog_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeroapicalllog',
            name='process',
            field=models.CharField(choices=[('metadata', 'Update Metadata'), ('data', 'Sync Transactions & Journals'), ('journals', 'Process Journals'), ('trail-balance', 'Build Trail Balance'), ('pnl-by-tracking', 'Import P&L by Tracking'), ('reconcile', 'Reconcile Reports'), ('invoices', 'Sync Invoices'), ('quotes', 'Sync Quotes'), ('documents', 'Document Sync'), ('aged-payables', 'Sync Aged Payables'), ('aged-receivables', 'Sync Aged Receivables')], max_length=50),
        ),
    ]
