from django.urls import path
from apps.planning_analytics.views import (
    TM1CubesView,
    TM1CubeDimensionsView,
    TM1DimensionElementsView,
    TM1DimensionChildrenView,
    TM1PivotQueryView,
    PipelineRunView,
    TM1ExecuteView,
    TM1TestConnectionView,
    TM1ConfigView,
    TM1ProcessListView,
    UserTM1CredentialsView,
    TrackingMappingView,
    TrackingMappingAddView,
    CostCutReportView,
    KPITargetView,
    CostBehaviourView,
)

urlpatterns = [
    path('pipeline/run/', PipelineRunView.as_view(), name='planning-analytics-pipeline-run'),
    path('tm1/execute/', TM1ExecuteView.as_view(), name='planning-analytics-tm1-execute'),
    path('tm1/test-connection/', TM1TestConnectionView.as_view(), name='planning-analytics-tm1-test'),
    path('tm1/config/', TM1ConfigView.as_view(), name='planning-analytics-tm1-config'),
    path('tm1/processes/', TM1ProcessListView.as_view(), name='planning-analytics-tm1-processes'),
    path('tm1/cubes/', TM1CubesView.as_view(), name='pa-tm1-cubes'),
    path('tm1/cube-dimensions/', TM1CubeDimensionsView.as_view(), name='pa-tm1-cube-dimensions'),
    path('tm1/dimension-elements/', TM1DimensionElementsView.as_view(), name='pa-tm1-dimension-elements'),
    path('tm1/dimension-children/', TM1DimensionChildrenView.as_view(), name='pa-tm1-dimension-children'),
    path('tm1/query/', TM1PivotQueryView.as_view(), name='pa-tm1-query'),
    path('cost-cut/', CostCutReportView.as_view(), name='pa-cost-cut'),
    path('kpi-targets/', KPITargetView.as_view(), name='pa-kpi-targets'),
    path('cost-behaviour/', CostBehaviourView.as_view(), name='pa-cost-behaviour'),
    path('tm1/credentials/', UserTM1CredentialsView.as_view(), name='planning-analytics-tm1-credentials'),
    path('tm1/tracking-mapping/', TrackingMappingView.as_view(), name='planning-analytics-tracking-mapping'),
    path('tm1/tracking-mapping/add/', TrackingMappingAddView.as_view(), name='planning-analytics-tracking-mapping-add'),
]
