# Generated by Django 5.2.8 on 2026-02-08 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0001_initial'),
        ('xero_cube', '0003_alter_xerotrailbalance_balance_to_date'),
        ('xero_metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroPnlByTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('xero_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_by_tracking', to='xero_metadata.xeroaccount')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_by_tracking', to='xero_core.xerotenant')),
                ('tracking', models.ForeignKey(blank=True, help_text='Tracking option. NULL means unfiltered/overall P&L.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnl_by_tracking', to='xero_metadata.xerotracking')),
            ],
            options={
                'indexes': [models.Index(fields=['organisation', 'tracking', 'account', 'year', 'month'], name='pnl_trk_org_trk_acc_ym_idx')],
                'unique_together': {('organisation', 'tracking', 'account', 'year', 'month')},
            },
        ),
    ]
