# Generated by Django 5.2.8 on 2026-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_cube', '0004_add_xero_pnl_by_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerotrailbalance',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sum of journal line tax_amount for this account/period/contact/tracking.', max_digits=30),
        ),
    ]
