# Generated by Django 5.2.8 on 2026-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_cube', '0005_add_tax_amount_to_trail_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerotrailbalance',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Negative portion of amount (credit <= 0). debit + credit = amount.', max_digits=30),
        ),
        migrations.AddField(
            model_name='xerotrailbalance',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive portion of amount (debit >= 0). debit + credit = amount.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='xerotrailbalance',
            name='balance_to_date',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance to date (YTD) for balance sheet accounts (ASSET, LIABILITY, EQUITY) - cumulative sum of all periods up to and including current month', max_digits=30, null=True),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE xero_cube_xerotrailbalance
                SET debit  = GREATEST(amount, 0),
                    credit = LEAST(amount, 0)
                WHERE debit = 0 AND credit = 0 AND amount != 0;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
