# Generated by Django 5.2.14 on 2026-09-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xero_cube', '0006_add_debit_credit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='xerotrailbalance',
            name='tb_acc_contact_idx',
        ),
        migrations.RemoveIndex(
            model_name='xerotrailbalance',
            name='tb_org_acc_ct_idx',
        ),
    ]
