# Generated by Django 5.2.8 on 2026-02-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerotenant',
            name='tracking_category_1_id',
            field=models.CharField(blank=True, help_text='Xero TrackingCategoryID for slot 1 (first category from API). Stable even if name changes.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='xerotenant',
            name='tracking_category_2_id',
            field=models.CharField(blank=True, help_text='Xero TrackingCategoryID for slot 2 (second category from API).', max_length=64, null=True),
        ),
    ]
