# Generated by Django 5.2.17 on 2026-08-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_core', '0004_add_tenant_reauth_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroApiQuota',
            fields=[
                ('tenant_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('day_remaining', models.IntegerField(blank=True, help_text='X-DayLimit-Remaining from the most recently recorded Xero response.', null=True)),
                ('min_remaining', models.IntegerField(blank=True, help_text='X-MinLimit-Remaining from the most recently recorded Xero response.', null=True)),
                ('last_status', models.IntegerField(blank=True, help_text='HTTP status of the response the headers came from (e.g. 200, 429).', null=True)),
                ('seen_at', models.DateTimeField(help_text='When these headers were observed.')),
            ],
            options={
                'verbose_name': 'Xero API quota',
                'verbose_name_plural': 'Xero API quotas',
            },
        ),
    ]
