# Generated by Django 5.2.17 on 2026-08-21 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


CATALOGUE = (
    ('metadata', 'Metadata', True),
    ('transaction-journal-sync', 'Transaction and journal sync', True),
    ('invoice-sync', 'Invoice sync', True),
    ('process-journals', 'Process journals', True),
    ('trail-balance', 'Trial Balance', True),
    ('documents', 'Documents', False),
    ('aged-payables', 'Aged payables', False),
    ('aged-receivables', 'Aged receivables', False),
)


def provision_existing_entity_catalogues(apps, schema_editor):
    XeroTenant = apps.get_model('xero_core', 'XeroTenant')
    Definition = apps.get_model('web_api_v2', 'IngestSourceJobDefinition')
    rows = []
    for entity_id in XeroTenant.objects.values_list('tenant_id', flat=True).iterator():
        for key, label, required in CATALOGUE:
            rows.append(Definition(
                entity_id=entity_id,
                key=key,
                source_family='XERO',
                label=label,
                required=required,
                configuration_state='CONFIGURED',
                supported_operations=[key],
                read_capabilities=['VIEW_STATUS'],
            ))
    Definition.objects.bulk_create(rows, ignore_conflicts=True, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('web_api_v2', '0001_initial'),
        ('xero_core', '0005_xeroapiquota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestProcessRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_key', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked')], default='queued', max_length=16)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('periods', models.JSONField(blank=True, default=list)),
                ('records_summary', models.JSONField(blank=True, default=dict)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=240)),
                ('retryable', models.BooleanField(default=False)),
                ('blocked_reason', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingest_process_runs', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_process_runs', to='xero_core.xerotenant')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='web_api_v2.ingestprocessrun')),
            ],
            options={
                'ordering': ('-requested_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='IngestProcessAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_key', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('result_state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked')], max_length=16)),
                ('correlation_id', models.UUIDField()),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xero_core.xerotenant')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='web_api_v2.ingestprocessrun')),
            ],
            options={
                'ordering': ('occurred_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='IngestSourceJobDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('source_family', models.CharField(choices=[('XERO', 'Xero'), ('INVESTEC', 'Investec'), ('MANUAL', 'Manual'), ('PLANNING_ANALYTICS', 'Planning Analytics')], max_length=32)),
                ('label', models.CharField(max_length=160)),
                ('required', models.BooleanField(default=True)),
                ('configuration_state', models.CharField(choices=[('CONFIGURED', 'Configured'), ('NOT_CONFIGURED', 'Not configured'), ('DISABLED', 'Disabled')], default='CONFIGURED', max_length=32)),
                ('supported_operations', models.JSONField(blank=True, default=list)),
                ('read_capabilities', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_source_job_definitions', to='xero_core.xerotenant')),
            ],
            options={
                'ordering': ('entity_id', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='UserEntityCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('RUN_INGESTION_PROCESS', 'Run ingestion process')], max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to='web_api_v2.userentitymembership')),
            ],
        ),
        migrations.AddIndex(
            model_name='ingestprocessrun',
            index=models.Index(fields=['entity', 'process_key', '-requested_at'], name='web_api_v2_run_process_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestprocessrun',
            index=models.Index(fields=['entity', 'state', '-requested_at'], name='web_api_v2_run_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestprocessrun',
            constraint=models.UniqueConstraint(fields=('entity', 'idempotency_key'), name='web_api_v2_unique_entity_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='ingestprocessrun',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('queued', 'running'))), fields=('entity',), name='web_api_v2_one_active_entity_ingest'),
        ),
        migrations.AddIndex(
            model_name='ingestprocessauditevent',
            index=models.Index(fields=['entity', '-occurred_at'], name='web_api_v2_audit_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestsourcejobdefinition',
            index=models.Index(fields=['entity', 'active'], name='web_api_v2_source_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestsourcejobdefinition',
            constraint=models.UniqueConstraint(fields=('entity', 'key'), name='web_api_v2_unique_entity_source_job'),
        ),
        migrations.AddIndex(
            model_name='userentitycapability',
            index=models.Index(fields=['membership', 'active'], name='web_api_v2_cap_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='userentitycapability',
            constraint=models.UniqueConstraint(fields=('membership', 'code'), name='web_api_v2_unique_membership_capability'),
        ),
        migrations.RunPython(provision_existing_entity_catalogues, migrations.RunPython.noop),
    ]
