# Generated by Django 5.2.14 on 2026-08-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api_v2', '0003_ingestprocessrunperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentitycapability',
            name='code',
            field=models.CharField(choices=[('RUN_INGESTION_PROCESS', 'Run ingestion process'), ('MANAGE_SHARE_MAPPINGS', 'Manage share-name mappings')], max_length=64),
        ),
    ]
