# Generated by Django 5.2.17 on 2026-08-20 04:19
#
# Creates the three Django-managed findings tables (audit_auditfinding,
# audit_auditfindingcomment, audit_auditfindingattachment) in the default
# schema. The first three CreateModel operations (AuditCheck / AuditCheckRun /
# AuditCheckResult) are STATE-ONLY: those models are managed=False over the raw
# Postgres schema ``audit`` (created by 0001's RunSQL) and were never in
# Django's migration state, so makemigrations records them here. Django emits
# NO SQL for unmanaged models — verified via sqlmigrate: they render as
# "-- (no-op)" and audit.checks / check_runs / check_results are never touched.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCheck',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('sql_text', models.TextField()),
                ('expected', models.CharField(max_length=16)),
                ('owner_action', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'audit"."checks',
                'ordering': ['code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditCheckResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=8)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('sample_rows', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'audit"."check_results',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditCheckRun',
            fields=[
                ('run_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fy', models.IntegerField()),
                ('tenant_id', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit"."check_runs',
                'ordering': ['-run_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.IntegerField(db_index=True)),
                ('ref', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(default='MEDIUM', max_length=16)),
                ('status', models.CharField(db_index=True, default='OPEN', max_length=16)),
                ('category', models.CharField(blank=True, default='OTHER', max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='ZAR', max_length=8)),
                ('description', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('owner', models.CharField(blank=True, default='', max_length=150)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=200)),
                ('check_code', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('asana_gid', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fy', 'ref'],
                'indexes': [models.Index(fields=['fy', 'status'], name='audit_audit_fy_5689bc_idx'), models.Index(fields=['fy', 'severity'], name='audit_audit_fy_06ab13_idx')],
                'constraints': [models.UniqueConstraint(fields=('fy', 'ref'), name='uniq_auditfinding_ref_per_fy')],
            },
        ),
        migrations.CreateModel(
            name='AuditFindingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audit_findings/%Y/%m/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.BigIntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='audit.auditfinding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFindingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='audit.auditfinding')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
