# Generated by Django 5.2.17 on 2026-08-20 04:27

#
# Findings register, addendum 2: the saved-pivot fields on a finding
# (cube_view / cube_note), the AuditFindingLink edge table, and the attachment
# storage path moving from audit_findings/%Y/%m/ to audit_findings/<fy>/<id>/.
#
# Zero-downtime classification: TRIVIAL.
#   - Both AddFields are nullable / have a default and add no NOT NULL, so the
#     ALTER TABLE is a catalog-only change on PG11+ (no table rewrite).
#   - The AlterField on `file` changes only upload_to, which is Python-side;
#     Django emits no SQL for it.
#   - CreateModel builds a new empty table; nothing to backfill.
# The findings register holds tens of rows today, but this is safe at any size.
#
# The (kind, ref) index on AuditFindingLink is load-bearing, not decoration: it
# is the REVERSE lookup ("which findings cite this slip") that audit.v_finding_graph
# in 0004 traverses. Do not drop it.

import apps.audit.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='cube_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='cube_view',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditfindingattachment',
            name='file',
            field=models.FileField(upload_to=apps.audit.models.finding_attachment_path),
        ),
        migrations.CreateModel(
            name='AuditFindingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('ref', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=300)),
                ('added_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='audit.auditfinding')),
            ],
            options={
                'ordering': ['kind', 'id'],
                'indexes': [models.Index(fields=['kind', 'ref'], name='audit_audit_kind_71b79b_idx')],
                'constraints': [models.UniqueConstraint(fields=('finding', 'kind', 'ref'), name='uniq_findinglink')],
            },
        ),
    ]
