# Generated by Django 5.2.17 on 2026-08-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_finding_graph_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfindingattachment',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
