# Generated by Django 5.2.14 on 2026-09-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_attachment_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_kind', models.CharField(choices=[('receipt', 'Receipt'), ('finding', 'Finding')], db_index=True, max_length=16)),
                ('comment_id', models.BigIntegerField(db_index=True)),
                ('author', models.CharField(blank=True, default='', max_length=150)),
                ('target_url', models.URLField(max_length=500)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('response_snippet', models.TextField(blank=True, default='')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Comment webhook delivery',
                'verbose_name_plural': 'Comment webhook deliveries',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddField(
            model_name='auditfindingcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='audit.auditfindingcomment'),
        ),
        migrations.AlterField(
            model_name='auditfindingcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
