# Generated by Django 5.2.14 on 2026-09-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_commentwebhookdelivery_auditfindingcomment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentwebhookdelivery',
            name='comment_kind',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('finding', 'Finding'), ('cube_comment', 'Cube comment')], db_index=True, max_length=16),
        ),
    ]
