# Generated by Django 5.2.8 on 2026-03-11 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_investments', '0001_initial'),
        ('investec', '0024_add_share_name_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='share_name_mapping',
            field=models.OneToOneField(blank=True, help_text='Link to Investec JSE share name mapping for additional share data (share_name, company, share_code).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_symbol', to='investec.investecjsesharenamemapping'),
        ),
    ]
