# Generated by Django 5.2.8 on 2026-03-11 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_investments', '0002_add_share_name_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='category',
            field=models.CharField(blank=True, choices=[('equity', 'Equity'), ('etf', 'ETF'), ('index', 'Index'), ('forex', 'Forex')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='AnalystPriceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_price_target', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'Analyst price target',
                'verbose_name_plural': 'Analyst price targets',
            },
        ),
        migrations.CreateModel(
            name='AnalystRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=list)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_recommendations', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'Analyst recommendation',
                'verbose_name_plural': 'Analyst recommendations',
            },
        ),
        migrations.CreateModel(
            name='EarningsEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_estimate', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'Earnings estimate',
                'verbose_name_plural': 'Earnings estimates',
            },
        ),
        migrations.CreateModel(
            name='EarningsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(blank=True, db_index=True, null=True)),
                ('freq', models.CharField(max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_reports', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'Earnings report',
                'verbose_name_plural': 'Earnings reports',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News items',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'Symbol info',
                'verbose_name_plural': 'Symbol infos',
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'Dividend',
                'verbose_name_plural': 'Dividends',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='fi_dividend_symbol_date_unique')],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('income_stmt', 'Income statement'), ('balance_sheet', 'Balance sheet'), ('cash_flow', 'Cash flow')], db_index=True, max_length=20)),
                ('period_end', models.DateField(blank=True, db_index=True, null=True)),
                ('freq', models.CharField(choices=[('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('trailing', 'Trailing')], default='yearly', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'Financial statement',
                'verbose_name_plural': 'Financial statements',
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'statement_type', 'freq'), name='fi_stmt_symbol_type_freq_unique')],
            },
        ),
        migrations.CreateModel(
            name='OwnershipSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_type', models.CharField(choices=[('institutional', 'Institutional'), ('major', 'Major'), ('insider_transactions', 'Insider transactions')], db_index=True, max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_snapshots', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'Ownership snapshot',
                'verbose_name_plural': 'Ownership snapshots',
                'ordering': ['-fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'holder_type'), name='fi_ownership_symbol_type_unique')],
            },
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='financial_investments.symbol')),
            ],
            options={
                'verbose_name': 'Split',
                'verbose_name_plural': 'Splits',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='fi_split_symbol_date_unique')],
            },
        ),
    ]
