# Generated by Django 5.2.8 on 2026-03-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_investments', '0003_add_extra_data_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistTablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default='default', max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Watchlist table preference',
                'verbose_name_plural': 'Watchlist table preferences',
            },
        ),
    ]
