# Generated by Django 5.2.11 on 2026-03-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_investments', '0004_watchlist_table_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_date', models.DateField(blank=True, null=True)),
                ('ex_dividend_date', models.DateField(blank=True, db_index=True, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('paid', 'Paid'), ('estimated', 'Estimated')], db_index=True, default='declared', max_length=20)),
                ('source', models.CharField(blank=True, help_text='e.g. yfinance, manual', max_length=50)),
                ('tm1_adjustment_written', models.BooleanField(default=False, help_text='Whether the TM1 budget adjustment has been applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dividend calendar',
                'verbose_name_plural': 'Dividend calendar entries',
                'ordering': ['-ex_dividend_date', '-declaration_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='dividend',
            name='fi_dividend_symbol_date_unique',
        ),
        migrations.AddField(
            model_name='dividend',
            name='dividend_type',
            field=models.CharField(choices=[('dividend_declared', 'Dividend declared'), ('dividend_paid', 'Dividend paid')], db_index=True, default='dividend_paid', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='dividend',
            constraint=models.UniqueConstraint(fields=('symbol', 'date', 'dividend_type'), name='fi_dividend_symbol_date_type_unique'),
        ),
        migrations.AddField(
            model_name='dividendcalendar',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_calendar', to='financial_investments.symbol'),
        ),
        migrations.AddConstraint(
            model_name='dividendcalendar',
            constraint=models.UniqueConstraint(fields=('symbol', 'ex_dividend_date'), name='fi_divcal_symbol_exdate_unique'),
        ),
    ]
