# Generated by Django 5.2.8 on 2026-02-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TM1ProcessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'TM1 Process Config',
                'verbose_name_plural': 'TM1 Process Configs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TM1ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(max_length=500)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TM1 Server Config',
                'verbose_name_plural': 'TM1 Server Configs',
            },
        ),
    ]
