# Generated by Django 5.2.11 on 2026-03-13 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_analytics', '0004_fix_trail_balance_process_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTM1Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm1_username', models.CharField(max_length=200)),
                ('tm1_password', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tm1_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User TM1 Credentials',
                'verbose_name_plural': 'User TM1 Credentials',
            },
        ),
    ]
