# Generated by Django 5.2.14 on 2026-06-03 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_analytics', '0005_user_tm1_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=200)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=300)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('direction', models.CharField(choices=[('lower_is_better', 'Lower is better'), ('higher_is_better', 'Higher is better')], default='lower_is_better', max_length=20)),
                ('amber_band_pct', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Target',
                'verbose_name_plural': 'KPI Targets',
                'ordering': ['entity_id', 'period_year', 'metric_key'],
                'constraints': [models.UniqueConstraint(fields=('metric_key', 'entity_id', 'period_year'), name='uniq_kpi_target_metric_entity_year')],
            },
        ),
    ]
