# Generated by Django 5.2.14 on 2026-06-03 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_analytics', '0006_kpitarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_key', models.CharField(max_length=120, unique=True)),
                ('behaviour', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('semi_variable', 'Semi-variable'), ('non_controllable', 'Non-controllable')], max_length=20)),
                ('driver', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(default='cfo_seed', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_behaviours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Behaviour',
                'verbose_name_plural': 'Cost Behaviours',
                'ordering': ['account_key'],
            },
        ),
    ]
