# Generated by Django 5.2.14 on 2026-06-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_analytics', '0007_costbehaviour'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbehaviour',
            name='cuttability',
            field=models.CharField(choices=[('T0', 'Not a target'), ('T1', 'Quick win'), ('T2', 'Behavioural'), ('T3', 'Discretionary'), ('T4', 'Renegotiable'), ('T5', 'Structural')], default='T2', max_length=2),
        ),
        migrations.AddField(
            model_name='costbehaviour',
            name='is_addressable',
            field=models.BooleanField(default=True),
        ),
    ]
