# Generated by Django 5.2.14 on 2026-06-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_analytics', '0008_costbehaviour_cuttability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbehaviour',
            name='is_manageable',
            field=models.BooleanField(default=False),
        ),
    ]
