# Generated by Django 5.2.14 on 2026-08-28 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_analytics', '0009_costbehaviour_is_manageable'),
        ('xero_core', '0005_xeroapiquota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPlanningTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Human name for the destination, e.g. "PA Production · Finance".', max_length=200)),
                ('workspace', models.CharField(help_text='Cube or application path within TM1, e.g. "Group Finance / General Ledger".', max_length=300)),
                ('default_scenario', models.CharField(blank=True, default='', max_length=120)),
                ('default_version', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(help_text='The Xero tenant whose data this destination receives.', on_delete=django.db.models.deletion.CASCADE, related_name='planning_targets', to='xero_core.xerotenant')),
                ('server', models.ForeignKey(help_text='TM1 server. Its credentials never leave the server side.', on_delete=django.db.models.deletion.PROTECT, related_name='entity_targets', to='planning_analytics.tm1serverconfig')),
            ],
            options={
                'verbose_name': 'Entity Planning Target',
                'verbose_name_plural': 'Entity Planning Targets',
                'ordering': ['entity_id', 'display_name'],
                'indexes': [models.Index(fields=['entity', 'active'], name='pa_target_entity_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('entity',), name='pa_one_active_target_per_entity')],
            },
        ),
    ]
