# Generated by Django 4.2.27 on 2025-12-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestecTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('account_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('share_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investec Transaction',
                'verbose_name_plural': 'Investec Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
