# Generated by Django 4.2.27 on 2025-12-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestecTransaction',
            new_name='InvestecJseTransaction',
        ),
    ]
