# Generated by Django 4.2.27 on 2025-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0002_rename_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investecjsetransaction',
            name='share_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
