# Generated by Django 4.2.27 on 2025-12-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0003_allow_blank_share_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestecJsePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('share_code', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('currency', models.CharField(default='ZAR', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('move_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('portfolio_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('annual_income_zar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investec Portfolio',
                'verbose_name_plural': 'Investec Portfolios',
                'ordering': ['-date', 'company'],
                'indexes': [models.Index(fields=['date', 'company'], name='investec_in_date_a58902_idx'), models.Index(fields=['share_code'], name='investec_in_share_c_0ea75c_idx')],
            },
        ),
    ]
