# Generated by Django 4.2.27 on 2025-12-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0004_investecjseportfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investecjseportfolio',
            options={'ordering': ['-date', 'company'], 'verbose_name': 'Investec Jse Portfolio', 'verbose_name_plural': 'Investec Jse Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='investecjsetransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Investec Jse Transaction', 'verbose_name_plural': 'Investec Jse Transactions'},
        ),
        migrations.AddField(
            model_name='investecjseportfolio',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investecjseportfolio',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investecjseportfolio',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investecjsetransaction',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investecjsetransaction',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investecjsetransaction',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='investecjseportfolio',
            index=models.Index(fields=['year', 'month'], name='investec_in_year_cdf2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='investecjsetransaction',
            index=models.Index(fields=['year', 'month'], name='investec_in_year_21b5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='investecjsetransaction',
            index=models.Index(fields=['date'], name='investec_in_date_dabe70_idx'),
        ),
    ]
