# Generated by Django 4.2.27 on 2025-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0005_alter_investecjseportfolio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareNameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('company', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('share_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Share Name Mapping',
                'verbose_name_plural': 'Share Name Mappings',
                'ordering': ['share_name'],
                'indexes': [models.Index(fields=['share_name'], name='investec_sh_share_n_561c2b_idx'), models.Index(fields=['company'], name='investec_sh_company_603842_idx'), models.Index(fields=['share_code'], name='investec_sh_share_c_2240f4_idx')],
            },
        ),
    ]
