# Generated by Django 4.2.27 on 2025-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0008_rename_action_to_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='investecjsesharenamemapping',
            new_name='investec_in_share_n_36ab1a_idx',
            old_name='investec_sh_share_n_561c2b_idx',
        ),
        migrations.RenameIndex(
            model_name='investecjsesharenamemapping',
            new_name='investec_in_company_25c483_idx',
            old_name='investec_sh_company_603842_idx',
        ),
        migrations.RenameIndex(
            model_name='investecjsesharenamemapping',
            new_name='investec_in_share_c_f15456_idx',
            old_name='investec_sh_share_c_2240f4_idx',
        ),
        migrations.AddField(
            model_name='investecjsetransaction',
            name='price_per_share_cents',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
