# Generated by Django 4.2.27 on 2025-12-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0012_sharemonthlyperformance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sharemonthlyperformance',
            new_name='investec_sh_share_n_e5ca0b_idx',
            old_name='investec_sh_share_n_idx',
        ),
        migrations.RenameIndex(
            model_name='sharemonthlyperformance',
            new_name='investec_sh_date_fec34d_idx',
            old_name='investec_sh_date_idx',
        ),
        migrations.AlterField(
            model_name='sharemonthlyperformance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sharemonthlyperformance',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
