# Generated by Django 4.2.27 on 2025-12-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0013_rename_investec_sh_share_n_idx_investec_sh_share_n_e5ca0b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharemonthlyperformance',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sharemonthlyperformance',
            name='total_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
