# Generated by Django 4.2.27 on 2025-12-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0015_rename_to_investecjsesharemonthlyperformance_and_add_year_month'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='investecjsesharemonthlyperformance',
            new_name='investec_in_share_n_53fe0e_idx',
            old_name='investec_sh_share_n_e5ca0b_idx',
        ),
        migrations.RenameIndex(
            model_name='investecjsesharemonthlyperformance',
            new_name='investec_in_date_17125b_idx',
            old_name='investec_sh_date_fec34d_idx',
        ),
        migrations.RenameIndex(
            model_name='investecjsesharemonthlyperformance',
            new_name='investec_in_year_b1c49d_idx',
            old_name='investec_js_year_mon_idx',
        ),
    ]
