# Generated by Django 4.2.27 on 2025-12-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0017_add_dividend_type_and_investec_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='investecjsesharemonthlyperformance',
            new_name='investec_in_dividen_430afb_idx',
            old_name='investec_js_dividend_idx',
        ),
        migrations.RenameIndex(
            model_name='investecjsesharemonthlyperformance',
            new_name='investec_in_investe_b63424_idx',
            old_name='investec_js_account_idx',
        ),
    ]
