# Generated by Django 5.2.8 on 2026-02-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0019_remove_duplicate_share_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='investecjsesharenamemapping',
            name='share_name2',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investecjsesharenamemapping',
            name='share_name3',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='investecjsesharenamemapping',
            index=models.Index(fields=['share_name2'], name='investec_in_share_n_d8c773_idx'),
        ),
        migrations.AddIndex(
            model_name='investecjsesharenamemapping',
            index=models.Index(fields=['share_name3'], name='investec_in_share_n_20b493_idx'),
        ),
    ]
