# Generated by Django 5.2.8 on 2026-03-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0023_add_investec_bank_sync_log'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investecbanktransaction',
            name='investec_bank_txn_account_posting_order',
        ),
        migrations.RenameIndex(
            model_name='investecbanktransaction',
            new_name='investec_in_account_314359_idx',
            old_name='investec_in_account_8a1f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='investecbanktransaction',
            new_name='investec_in_status_e7f79b_idx',
            old_name='investec_in_status_2c4b8b_idx',
        ),
        migrations.AddConstraint(
            model_name='investecbanktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('posting_date__isnull', False), ('posted_order__isnull', False)), fields=('account', 'posting_date', 'posted_order'), name='investec_bank_txn_account_posting_order'),
        ),
    ]
