# Generated by Django 5.2.14 on 2026-06-09
# Owner label on InvestecBankAccount for personal-expenses grouping.
# (Kept to just this field — unrelated InvestecJsePortfolio model drift is left
# for a separate, intentional migration.)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0024_add_share_name_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='investecbankaccount',
            name='owner',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Person who owns this account (e.g. 'MC', 'Wife'). Used for personal-expenses grouping.",
                max_length=70,
            ),
        ),
    ]
