# Generated by Django 5.2.14 on 2026-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0026_v_cash_actuals_weekly'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, help_text='Forecast run identifier. A regenerate replaces all rows for (run_id, scenario).', max_length=64)),
                ('run_date', models.DateField(db_index=True, help_text='Anchor date the run was generated from (week-1 start).')),
                ('scenario', models.CharField(db_index=True, max_length=32)),
                ('week_start_date', models.DateField(db_index=True)),
                ('week_index', models.IntegerField(help_text='1-based week number within the run (1..weeks).')),
                ('entity', models.CharField(blank=True, max_length=40)),
                ('capacity', models.CharField(blank=True, max_length=16)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_internal', models.BooleanField(default=False, help_text='True for inter-company flows that ELIMINATE at group level (one economic unit).')),
                ('source', models.CharField(blank=True, help_text="Provenance: 'prototype', 'rule:recurring', 'rule:vat', etc.", max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cashflow Forecast Row',
                'verbose_name_plural': 'Cashflow Forecast Rows',
                'ordering': ['run_id', 'scenario', 'week_index', 'direction', 'category'],
                'indexes': [models.Index(fields=['run_id', 'scenario', 'week_index'], name='investec_ca_run_id_3cef37_idx'), models.Index(fields=['scenario', 'run_date'], name='investec_ca_scenari_b53673_idx')],
            },
        ),
    ]
