# Generated by Django 5.2.14 on 2026-08-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0029_fix_v_cash_actuals_weekly_close_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestecBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_profile', models.CharField(blank=True, db_index=True, max_length=40)),
                ('profile_id', models.CharField(blank=True, db_index=True, max_length=70)),
                ('beneficiary_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('reference_account_number', models.CharField(blank=True, max_length=50)),
                ('reference_name', models.CharField(blank=True, max_length=200)),
                ('category_id', models.CharField(blank=True, max_length=50)),
                ('faster_payment_allowed', models.BooleanField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('cell_no', models.CharField(blank=True, max_length=40)),
                ('email_address', models.CharField(blank=True, max_length=254)),
                ('collection', models.JSONField(blank=True, help_text='Raw API payload for this beneficiary.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investec Beneficiary',
                'verbose_name_plural': 'Investec Beneficiaries',
                'ordering': ['name', 'beneficiary_name'],
                'constraints': [models.UniqueConstraint(fields=('source_profile', 'beneficiary_id'), name='investec_beneficiary_profile_benid')],
            },
        ),
    ]
