# Generated by Django 5.2.14 on 2026-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0030_investecbeneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investecjseportfolio',
            name='move_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='investecjseportfolio',
            name='portfolio_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
