# Generated by Django 5.2.14 on 2026-08-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investec', '0031_alter_investecjseportfolio_move_percent_and_more'),
        ('xero_core', '0005_xeroapiquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestecEntityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Investec account number, exactly as it appears on the source rows.', max_length=50)),
                ('kind', models.CharField(choices=[('BANK', 'Bank account'), ('SHARE', 'Share trading account')], db_index=True, max_length=8)),
                ('label', models.CharField(blank=True, default='', help_text='Optional human name. The account number is never shown to the browser.', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(help_text='The Xero tenant whose books this account belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='investec_accounts', to='xero_core.xerotenant')),
            ],
            options={
                'verbose_name': 'Investec entity account',
                'verbose_name_plural': 'Investec entity accounts',
                'ordering': ['entity_id', 'kind', 'account_number'],
                'indexes': [models.Index(fields=['entity', 'kind', 'active'], name='investec_entity_kind_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('account_number', 'kind'), name='investec_account_bound_once')],
            },
        ),
    ]
