# Generated by Django 5.2.8 on 2026-02-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerotracking',
            name='category_slot',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 or 2 based on GET TrackingCategories array order. Slot 1 = first category, slot 2 = second.', null=True),
        ),
    ]
