# Generated by Django 5.2.8 on 2026-02-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_metadata', '0002_add_category_slot_to_xerotracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerotracking',
            name='tracking_category_id',
            field=models.CharField(blank=True, help_text='Xero TrackingCategoryID - stable identifier, survives category renames.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='xerotracking',
            name='category_slot',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Deprecated: use org tracking_category_1_id/2_id + tracking_category_id. Kept for fallback.', null=True),
        ),
    ]
